version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: migrations
      MYSQL_USER: migrator
      MYSQL_PASSWORD: migrator
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"

  migrator:
    build: .
    depends_on:
      - db
      - rabbitmq
    environment:
      MYSQL_DSN: "migrator:migrator@tcp(db:3306)/migrations?parseTime=true"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
    ports:
      - "8080:8080"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  db-data:
