version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: migrations
      MYSQL_USER: migrator
      MYSQL_PASSWORD: migrator
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"

  migrator:
    build: .
    depends_on:
      - db
    environment:
      MYSQL_DSN: "migrator:migrator@tcp(db:3306)/migrations?parseTime=true"
    ports:
      - "8080:8080"

volumes:
  db-data:
